use GYSALES

SELECT*FROM SALES
-- Kayseri sehrine ait genel satis ozetleri
SELECT COUNT(*) SATIRSAYISI,
SUM(AMOUNT) TOPLAMADET,SUM(TOTALPRICE)TOPLAMSATIS,
AVG(AMOUNT) ORTALAMAADET
FROM SALES
WHERE CITY='Kayseri'

select*from SALES order by AMOUNT desc
-- GIDA kategorisindeki Istanbul satis ozetleri
SELECT
SUM(TOTALPRICE)as Toplamsatis,SUM(AMOUNT)as Toplamadet,
MIN(TOTALPRICE) as EndusuksatisT,MAX(TOTALPRICE)as EnyukseksarisT,
count(*) AS Satirsayisi,
AVG(TOTALPRICE) AS OrtalamaFiyat,
MIN(DATE_)AS IlkSatis,
MAX(DATE_)AS Sonsatis
FROM SALES 
WHERE CATEGORY1='GIDA'AND (CITY='Ýstanbul');

--SALES TABLOSUNDA CINSIYETE GORE TOPLAMDA KAÇ TEKIL MUSTERI OLUGUNU GOSTEREN SORGU 


SELECT COUNT(DISTINCT CUSTOMERID) FROM SALES --CÝNSÝYETÝ KADIN OLAN MÜSTERÝELR BURDA DISTINC TEKÝLLEÞTÝREM YAPIYOR
WHERE CUSTOMERGENDER='K'

--GROUPBY KULLANIMI


SELECT REGION, COUNT(*) SATISAYISI,SUM(TOTALPRICE) TOPLAMSATIS    FROM SALES
--WHERE CITY IN ('Ýstanbul','Ankara')
GROUP BY REGION
ORDER BY REGION

SELECT*FROM SALES
--GIDA KATEGORISINDE ANKARA ISTANBUL ICIN MAGAZA ADI TOPLAM SATIS TUTAR VE ADEDI EN DUSUK  EN YUKSEK FIYAT
--TOPLAM KAÇ SATIR URUN SATILDI YAZAR KASADA BIR OKUTMA ISLEMINI ORTMALAA NE AKDAR TUTTUÐU ILK VE SON SATIÞ TARIHI

SELECT CITY, COUNT(*) SATISSAYISI,SUM(TOTALPRICE) TOPLAMSATIS,   
SUM(AMOUNT) TOPLAMSATISADEDI,
MIN(TOTALPRICE) AS ENDUSUKSATIS,
MAX(TOTALPRICE) AS ENYUKSEKSATIS,
AVG(TOTALPRICE) AS ORTALAMAFIYAT,
MIN(DATE_) ILKSATIS,
MAX(DATE_) SONSATIS

FROM SALES
WHERE  CATEGORY1='Gýda' and CITY IN ('Ýstanbul','Ankara')
GROUP BY CITY

-- SALES TABLOSUNDA SEHIRLER GORE TOPLAM YAPILAN SATISALRI GETIREN SORGU

SELECT CITY,
SUM(TOTALPRICE) AS TOPLAMSATIS,
SUM(AMOUNT) AS TOPLAMMIKTAR
FROM SALES
GROUP BY CITY
ORDER BY CITY

--sales tablosunda seCilen bir Sehrin tarihe göre sapýlan satýslarýný listeleyiniz

SELECT CITY, CONVERT(DATE,DATE_)DATE_, SUM(TOTALPRICE)AS TOPLAMSATÝS,--convert ile tarih icinden saatlerden kurtulduk soruda oyle istendigi icin
SUM(AMOUNT)AS TOPLAMADET
FROM SALES
WHERE CITY='Ýstanbul'
GROUP BY CITY, CONVERT(DATE,DATE_)--buraya koyma sebebizmizde tekrar eden verilerden kurtulmak
ORDER BY 2

--Sales tablosunda haftanýn gunlerine göre yapýlan toplam satýslarý getiren sorgu
SET LANGUAGE TURKISH
SELECT*FROM SALES
--DATEPART(DW HAFTANIN GUNU YEAR YILI MONTH AY BILGISI ALINABIIR  )
SELECT DATEPART(DW, '2022-09-10 08:53:55.190')
--GÜN ADLARI ÝÇÝN
SELECT DATENAME(DW, '2022-09-10 08:53:55.190')

SET LANGUAGE Turkish-- dili Turkce yapýp günleri Turkce getirdik

SELECT

DATENAME(DW,DATE_) GUNU,
SUM(TOTALPRICE) TOPLAMSATIS,
SUM(AMOUNT) TOPLAMSATIS

FROM SALES
GROUP BY DATEPART(DW,DATE_),DATENAME(DW,DATE_)
ORDER BY DATEPART(DW,DATE_)

--herbir urun kategorisinin altýnda encok satýs yapýlan ikinci katagoriye göre sýralanmýs sekilde satýslarý getiren sorgu

SELECT CATEGORY1,CATEGORY2, 
SUM(TOTALPRICE)AS TOTALPRICE



FROM SALES
GROUP BY CATEGORY1,CATEGORY2
ORDER BY CATEGORY1, TOTALPRICE DESC

--HAVING KULLANIMI
-- TOPLAM SATIS CUROSU 2MILYON TLNIN UZERINDE OLAN MAGAZALARI GETIREN SORGU
SELECT
CITY,
SUM(TOTALPRICE) AS TOPLAMSATIS

FROM SALES
GROUP BY CITY
HAVING SUM(TOTALPRICE)>2000000
ORDER BY CITY

--TEKIL MUSTERI SAYISI 1000 DEN FAZLA OLAN MAGAZALRIN TOPLAM SATISALRINI VE 
--BIR MUSTERININ ORTALAMA YAPTIGI ALISVERIS TUTARINI GETIREN SORGU--


SELECT
CITY, SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERID) MUSTERISAYISI,
SUM(TOTALPRICE)/COUNT(DISTINCT CUSTOMERID) AS ORTALAMATUTAR

FROM SALES
GROUP BY CITY
HAVING COUNT(DISTINCT CUSTOMERID)>1000
ORDER BY MUSTERISAYISI DESC


