USE GYSALES_RDMS_FULL
--HERBIR KULLANICININ SAHIP OLDUGU ADRES SAYISI JOIN ILE--

SELECT
U.NAMESURNAME ADI,
COUNT(A.ID) IDSAYISI

FROM USERS U 
JOIN ADDRESS A ON A.USERID=U.ID
GROUP BY U.NAMESURNAME
--HERBIR KULLANICININ SAHIP OLDUÐU ADRES SAYISI SUBQUERY ILE--

SELECT 
U.ID KULLANICI_ID,
U.NAMESURNAME ADSOYAD,
(SELECT
COUNT(*)
FROM ADDRESS
WHERE USERID=U.ID ) ADRES_SAYISI
FROM USERS U

--SEHRI ISTANBUL OLAN SATISALRI GETIREN SORGU JOIN ILE-

SELECT*FROM ORDERS O 
JOIN ADDRESS A ON A.ID=O.ADDRESSID
WHERE A.CITYID=34

-- SUBQUERY ILE --

SELECT*FROM ORDERS O
WHERE ADDRESSID  IN
(SELECT ID FROM ADDRESS WHERE CITYID=34)

 
 -- HER URUN ICIN TOPLAM SATIS ADEDI,TOPMA SATIS CIROSU,EN DUSUK SATIS FIYATI, EN YUKSEK SATIS FIYATI VE ORTALAMA--
 -- SATIS  FIYATINI GETIREN SORGU--

 SELECT
  I.ITEMCODE  URUN_KODU,
 I.ITEMNAME URUN_ADI,
 I.BRAND MARKA,
 I.CATEGORY1 KATAGORY,
 (SELECT SUM(AMOUNT)FROM ORDERDETAILS 
 WHERE ITEMID=I.ID) TOPLAM_ADET,
  (SELECT SUM(LINETOTAL)FROM ORDERDETAILS 
 WHERE ITEMID=I.ID) TOPLAM_CIRO,
  (SELECT MIN(UNITPRICE)FROM ORDERDETAILS 
 WHERE ITEMID=I.ID) EN_DUSUK_FIYAT,
  (SELECT MAX(UNITPRICE)FROM ORDERDETAILS 
 WHERE ITEMID=I.ID) EN_YUKSEK_FIYAT,
  (SELECT ROUND(AVG(UNITPRICE),2)FROM ORDERDETAILS 
 WHERE ITEMID=I.ID) ORTALAMA_FIYAT
 FROM ITEMS I

 -- HER MARKA ICIN TOPLAM URUN SAYISI TOPLAM ANA KATAGORI VE TOPLAM AT KATAGORI SAYISINI GETIREN SORGU--

 SELECT DISTINCT BRAND MARKA,
 ( SELECT
 COUNT(*)
 FROM ITEMS 
 WHERE BRAND=I.BRAND) URUN_SAYISI,

 ( SELECT
 COUNT(DISTINCT CATEGORY1) -- TEKRAR EDENLERDE DISTINCT KULLANDIK--
 FROM ITEMS 
 WHERE BRAND=I.BRAND
) ANA_KATAGORI_SAYISI,
 ( SELECT
 COUNT(DISTINCT CATEGORY2)
 FROM ITEMS 
 WHERE BRAND=I.BRAND
) ALT_KATAGORI_SAYISI
 FROM ITEMS I

 -- GIDA VE DETERJAN URULERINI SEHIRLERE GORE SATISLARI--
 SELECT
 C.CITY,
 (SELECT
 SUM(OD.LINETOTAL)
 FROM ORDERS O
 JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
 JOIN ADDRESS A ON A.ID=O.ADDRESSID
 JOIN ITEMS I ON I.ID=OD.ITEMID
 WHERE I.CATEGORY1='GIDA'AND A.CITYID=C.ID
 ) GIDA,
 (SELECT
 SUM(OD.LINETOTAL)
 FROM ORDERS O
 JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
 JOIN ADDRESS A ON A.ID=O.ADDRESSID
 JOIN ITEMS I ON I.ID=OD.ITEMID

 WHERE I.CATEGORY1='DETERJAN TEMÝZLÝK'AND A.CITYID=C.ID) DETERJAN_TEMIZLIK
 
 FROM CITIES C 


 --HERBIR SEHIR IÇIN TOPLAM KAÇ ERKEK KAÇ KADIN MUSTERI OLDUGUNU GETIRINIZ--

 SELECT 
 CITY SEHIR,
 ( SELECT 
 COUNT(DISTINCT USERID)
 FROM USERS U 
 JOIN ADDRESS A ON A.USERID=U.ID
 WHERE U.GENDER='K'AND A.CITYID=C.ID) KADIN_SAYISI,
  ( SELECT
 COUNT(DISTINCT USERID)
 FROM USERS U 
 JOIN ADDRESS A ON A.USERID=U.ID
 WHERE U.GENDER='E'AND A.CITYID=C.ID) ERKEK_SAYISI
 FROM CITIES C


 --HERBIR SEHIR IÇIN TOPLAM KAÇ ERKEK KAÇ KADIN MUSTERI OLDUGUNU GETIREN SORGU--
 -- EN COK MUSTERISI OLAN 10 SEHRI KADIN ERKEK DAGILIMI--

 SELECT TOP 10 
 CITY SEHIR,
 ( SELECT 
 COUNT(DISTINCT USERID)
 FROM USERS U 
 JOIN ADDRESS A ON A.USERID=U.ID
 WHERE U.GENDER='K'AND A.CITYID=C.ID) KADIN_SAYISI,
  ( SELECT
 COUNT(DISTINCT USERID)
 FROM USERS U 
 JOIN ADDRESS A ON A.USERID=U.ID
 WHERE U.GENDER='E'AND A.CITYID=C.ID) ERKEK_SAYISI,
 (SELECT 
 COUNT(DISTINCT USERID)
 FROM USERS U
 JOIN ADDRESS A ON A.USERID=U.ID
 WHERE A.CITYID=C.ID) AS TOPLAM_MUSTERI_SAYISI
 FROM CITIES C
 ORDER BY TOPLAM_MUSTERI_SAYISI DESC;




 -- SHIRLERIN AYLARA GORE SATISINI GETIREN SORGU--


 SELECT
 C.CITY SEHIR,
 ( SELECT
 SUM(O.TOTALPRICE)
 FROM ORDERS O
 JOIN ADDRESS A ON A.ID=O.ADDRESSID
 WHERE DATENAME(MONTH,O.DATE_)='OCAK' AND A.CITYID=C.ID) OCAK,
 ( SELECT
 SUM(O.TOTALPRICE)
 FROM ORDERS O
 JOIN ADDRESS A ON A.ID=O.ADDRESSID
 WHERE DATENAME(MONTH,O.DATE_)='ÞUBAT' AND A.CITYID=C.ID) ÞUBAT,
  ( SELECT
 SUM(O.TOTALPRICE)
 FROM ORDERS O
 JOIN ADDRESS A ON A.ID=O.ADDRESSID
 WHERE DATENAME(MONTH,O.DATE_)='MART' AND A.CITYID=C.ID) MART,
  ( SELECT
 SUM(O.TOTALPRICE)
 FROM ORDERS O
 JOIN ADDRESS A ON A.ID=O.ADDRESSID
 WHERE DATENAME(MONTH,O.DATE_)='Nisan' AND A.CITYID=C.ID) NISAN,
  ( SELECT
 SUM(O.TOTALPRICE)
 FROM ORDERS O
 JOIN ADDRESS A ON A.ID=O.ADDRESSID
 WHERE DATENAME(MONTH,O.DATE_)='MAYIS' AND A.CITYID=C.ID) MAYIS
 
 FROM CITIES C




 SET LANGUAGE turkish
 SELECT
 SUM(O.TOTALPRICE)
 FROM ORDERS O
 JOIN ADDRESS A ON A.ID=O.ADDRESSID
 WHERE DATENAME(MONTH,O.DATE_)='OCAK' AND A.CITYID=1









