USE GYSALES_RDMS_FULL

--2022 YILINDA OCAK AYINDA VERILEN SIPARISLERIN LISTESI--
SELECT O.DATE_,OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL,
I.ITEMCODE,I.BRAND,I.CATEGORY1,I.ITEMNAME
FROM ORDERS O
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID 
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE CONVERT(DATE,DATE_) BETWEEN '2022-01-01' AND '2022-01-31'
ORDER BY DATE_ DESC

SELECT*FROM USERS
SELECT*FROM ORDERS
SELECT*FROM ITEMS

SELECT*FROM ORDERDETAILS

--NAZMIYE ERCAN ISIMLI KULLANICIN VERDIGI SIPARISLERIN DETAYINI GETIREN SORGUYU YAZINIZ--

SELECT U.NAMESURNAME ISIM,
O.ID SIPARISNO,O.DATE_ SIPARISTARIHI,
I.ITEMCODE URUNKODU,I.BRAND MARKA,I.CATEGORY1 KATAGORI1,I.CATEGORY2 KATAGORI2
FROM USERS U
JOIN ORDERS O ON O.USERID=U.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON OD.ITEMID=I.ID
WHERE NAMESURNAME='NAZMÝYE ERCAN'
--SEHIRLERIN ILCELERINI GETIREN SORGU
SELECT C.CITY,T.TOWN
FROM CITIES C 
JOIN TOWNS T ON T.CITYID=C.ID 
ORDER BY CITY,TOWN

-- ISTANBULDA HANGI ILCEDE NE KADAR MUSTERI OLDUGUNU GETIREN SORGU--

SELECT 
T.TOWN ILCE,C.CITY,
COUNT( U.ID) AS MUSTERISAYISI
FROM CITIES C
JOIN TOWNS T ON T.CITYID=C.ID
JOIN ADDRESS A ON A.CITYID=C.ID
JOIN USERS U ON U.ID=A.USERID
WHERE C.CITY='Ýstanbul'
GROUP BY T.TOWN,C.CITY


------------------------------------------------
SELECT
C.CITY,T.TOWN,COUNT(DISTINCT U.ID)
FROM ADDRESS A
JOIN USERS U ON U.ID=A.USERID
JOIN CITIES C ON C.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
WHERE C.CITY='ÝSTANBUL'
GROUP BY T.TOWN,C.CITY


----------------------
--2022 YILINDA MART AYINDA 20-30 YAÞ ARASI MUSTERILERIN VERDIGI SIPARISLERI LISTELEYINIZ--

SELECT
 U.NAMESURNAME,
DATEDIFF(YEAR,BIRTHDATE,GETDATE())AS YAS,
C.CITY,O.DATE_ AS SIRAPRISTARIHI,O.ID SIPARISNO,O.TOTALPRICE AS TOPLAMTUTAR
FROM USERS U


JOIN ORDERS O ON O.USERID=U.ID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID

WHERE DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 20 AND 30 AND
 O.DATE_ BETWEEN '2022-03-01' AND '2022-03-31 23:59:59'


 SELECT
 U.NAMESURNAME KULLLANICI,DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) AS YAS,
 C.CITY SEHIR,O.DATE_ AS SIPARISTARIHI, O.ID SIPARISNO,O.TOTALPRICE AS TOPLAMTUTAR
 
FROM USERS U 
 JOIN ORDERS O ON O.USERID=U.ID
 JOIN ADDRESS A ON A.ID=O.ADDRESSID
 JOIN CITIES C ON C.ID=A.CITYID
 WHERE DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 20 AND 30
 AND O.DATE_ BETWEEN '2022-03-01' AND '2022-03-31 23:59:59'

 ---------------------------------------------------------------------
 --KULLANICILARIN HANGI SEHIRLERDE KAÇ ADRESI OLDUGU BILGISINI GETIRINIZ--
 SELECT U.ID AS KULLANICIID,U.NAMESURNAME ADSOYAD,C.CITY AS SEHIR, COUNT(A.ID)
 
 FROM USERS U
 JOIN ADDRESS A ON A.USERID=U.ID
 JOIN CITIES C ON C.ID=A.CITYID
 GROUP BY U.ID,U.NAMESURNAME,C.CITY
 ORDER BY U.NAMESURNAME

 ------------------------------------------------------------------------
 -- ISTANBULDA YILIN ILK 3 AYINDA EN ÇOK SATIS YAPILAN 10 URUNU GETIREN SORGUYU YAZINIZ--

 SELECT TOP 10  C.CITY,I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,
 SUM(OD.AMOUNT) OPLAMADET, SUM(OD.LINETOTAL) TOPLAMTUTAR
 FROM ORDERS O 
 JOIN ADDRESS A ON A.ID=O.ADDRESSID
 JOIN CITIES C ON C.ID=A.CITYID
 JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
 JOIN ITEMS I ON I.ID=OD.ITEMID

WHERE C.CITY='ÝSTANBUL' AND O.DATE_ BETWEEN '2022-01-01' AND '2022-03-31 23:59:59'
GROUP BY C.CITY,I.ITEMCODE,I.ITEMNAME,I.BRAND,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3
ORDER BY SUM(OD.LINETOTAL) DESC
----------------------------------------------------------
--HAFTANIN GUNLERINDE YAPILAN SATIS TUTARLARINI GETIREN SORGU--
SET LANGUAGE turkish
SELECT
DATENAME(WEEKDAY,O.DATE_) AS HAFTAGUNLERI,
COUNT(O.ID) SIPARISSAYISI,
SUM(TOTALPRICE) AS TOPLAMTUTAR
FROM ORDERS O 
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
GROUP BY DATEPART(DW,DATE_),DATENAME(WEEKDAY,O.DATE_)
ORDER BY DATEPART(DW,DATE_)

--SAAT ARALIGINA GORE NE KADAR ALISVERIS YAPILDIGINI GOSTEREN SQL SORGUSU--
-- ROUND VIRGÜLDEN SONRA HANELERI YUVARLAMAK ICIN--

SELECT 
DATEPART(HOUR,O.DATE_) SAAT,
ROUND(SUM(TOTALPRICE),0) TOPLAMTURAR, COUNT(ID) SIPARISSAYISI
FROM ORDERS O
GROUP BY DATEPART(HOUR,O.DATE_) 
ORDER BY SAAT ASC

--HER BIR SIPARISI ICIN TOPLAM SEVKETME SURESINI GETIREN SORGUYU YAZINIZ--

SELECT U.NAMESURNAME KULLANICI,
C.CITY SEHIR,
O.DATE_ SIPARISTARIHI,
I.DATE_ SEVKTARIHI,
DATEDIFF(HOUR,O.DATE_,I.DATE_) AS SEVKSURESI
FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID
JOIN CITIES C ON C.ID=A.CITYID
JOIN ORDERS O ON O.USERID=U.ID
JOIN INVOICES I ON I.ORDERID=O.ID
ORDER BY O.ID

--SIPARISLERIN GENEL OLARAK BOLGELERE GORE VE SEHIRELERE GORE ORTALAMA SEVKETME SURESINI GETIREN SORGU--
--- ORTALAMA SURE HESAPLANIRKEN 1.0 ILE CARPARSAKDA FLOAT DEGERE CEVIREBILIR--
---BILGE ICINDE C.REGION YAZIYORUZ OZAMANDA BOLGERELERIN ORTALAMA SIPARIS SEVK SURESINI BULABILIRZ--
SELECT 
C.CITY,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)*1.0) AS ORTALAMASEVKSAATI
FROM ADDRESS A 
JOIN CITIES C ON C.ID=A.CITYID
JOIN ORDERS O ON O.ADDRESSID=A.ID
JOIN INVOICES I ON I.ORDERID=O.ID
GROUP BY C.CITY

---- SIPARIS TARIHI AYI ILE FATURA TARIHI AYI FARKLI OLAN SIPARISLERI GETIREN SORGU--

SELECT O.ID SIPARISNO,
O.DATE_ SIPARISTARIHI,
I.DATE_ FATURATARIHI,
O.TOTALPRICE TOPLAMTURAR,
DATENAME(MONTH,O.DATE_) AS SIPARISAYI,
DATENAME(MONTH,I.DATE_) AS FATURAYI

FROM ORDERS O 
JOIN INVOICES I ON I.ORDERID=O.ID
WHERE DATENAME(MONTH,O.DATE_) !=DATENAME(MONTH,I.DATE_) 


-- SIPARIS TARIHI AYI ILE FATURA TARIHI AYI FARKLI OLAN SIPARISLERI GETIREN SORGU--

SELECT
O.ID AS SIPARISNO,
O.DATE_ AS SIPARISTARIHI,
I.DATE_ AS FATURATARIHI,
DATENAME(MONTH,O.DATE_) SIPARIS_AYI,
DATENAME(MONTH,I.DATE_)FATURA_AYI,
I.TOTALPRICE
FROM ORDERS O 
JOIN INVOICES I ON I.ORDERID=O.ID
WHERE DATENAME(MONTH,O.DATE_)  != DATENAME(MONTH,I.DATE_)
ORDER BY O.ID ASC

-- HER AY ICIN SIPARIS TARIHI ILE FATURA TARIHI AYI FARKLI OLAN SIPARIS SAYILARINI GETIRINIZ--

SET LANGUAGE Turkish
SELECT
DATENAME(MONTH,O.DATE_) SIPARIS_AYI,
COUNT(DATENAME(MONTH,I.DATE_))

FROM ORDERS O
JOIN INVOICES I ON I.ORDERID=O.ID
WHERE DATENAME(MONTH,O.DATE_)  != DATENAME(MONTH,I.DATE_)
GROUP BY DATENAME(MONTH,O.DATE_),DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(MONTH,O.DATE_)

-- HERBIR SEHIRDE NE KADAR ERKEK NE KADAR KADIN KULLANICI OLDUÐUNU GETIREN SORGU--

SELECT
C.CITY,
COUNT(U.ID) AS KULLANICI_SAYISI,
U.GENDER
FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY U.GENDER,C.CITY

-- URUN KATEGORILERINI ALFABETIK OLARAK ANA KATEGORI VE EN COK SATAN OLACAK SEKILDE GETIRINIZ--

SELECT 
I.CATEGORY1 ANA_KATAGORI,
I.CATEGORY2 ALT_KATAGORI,
SUM(OD.LINETOTAL) TOPLAMSATIS
FROM ITEMS I
JOIN ORDERDETAILS OD ON OD.ITEMID=I.ID
GROUP BY I.CATEGORY1,I.CATEGORY2
ORDER BY I.CATEGORY1 ASC,TOPLAMSATIS DESC --ALTARNATÝF ORDER BY 1,3 DESC--

-- DETERJAN TEMIZLIK VE GIDA KATEGORILERINDEKI URUNLERIN BOLGELERE GORE YAPILAN TOPLAM SATISLARINI GETIRINIZ--
SELECT 
C.REGION,
I.CATEGORY1,
SUM(OD.LINETOTAL)
FROM CITIES C 
JOIN ADDRESS A ON A.CITYID=C.ID
JOIN ORDERS O ON O.ADDRESSID=A.ID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE I.CATEGORY1='DETERJAN TEMÝZLÝK' OR CATEGORY1='GIDA'
GROUP BY C.REGION,I.CATEGORY1
ORDER BY C.REGION


-- HERBIR URUN ICIN TOPLAM NE KADARLIK SATIS YAPILDIGINI ADET VE TOPLAM CIRO OLARAK GETIRINIZ,
-- AYRICA HERBIR URUN ICIN EN DUSUK EN YUKSEK ORTALAMA SATIS VE MEVCUT FIYATA GORE KAR ZARAR HESABI YAPAN SORGU YAZINIZ

SELECT
I.ITEMCODE URUNKODU,
I.ITEMNAME URUN_ADI,
I.UNITPRICE LISTE_FIYATI,
SUM(OD.AMOUNT) TOPLAM_ADET,
ROUND(SUM(OD.LINETOTAL),0) TOPLAM_SATIS,
MIN(OD.UNITPRICE) ENDUSUKFIYAT,
MAX(OD.UNITPRICE) ENYUKSEKFIYAT,
ROUND(AVG(OD.UNITPRICE),2) ORTALAMAFIYAT,
SUM(I.UNITPRICE*OD.AMOUNT) LISTEFIYATINDAN_SATIS,
ROUND(SUM(OD.LINETOTAL)-SUM(I.UNITPRICE*OD.AMOUNT),0) KAR_ZARAR,
ROUND(100*(SUM(OD.LINETOTAL)-SUM(I.UNITPRICE*OD.AMOUNT))/SUM(I.UNITPRICE*OD.AMOUNT),2)  KAR_ZARARYUZDE
FROM ITEMS I 
JOIN ORDERDETAILS OD ON OD.ITEMID=I.ID

GROUP BY I.ITEMCODE,I.ITEMNAME,I.UNITPRICE
ORDER BY I.ITEMCODE

-- ALIS LISTE FIYATI VE SATIS FIYATI ILE SATILAN MIKTAR UZERINDEN EN COK KAR
-- EDILEN 10 URUN ILE EN AZ KAR EDILEN 10 URUNU LISTELEYINIZ
SELECT TOP 10*,
TOPLAM_SATIS-LISTEFIYATINDAN_SATIS AS KAR_ZARAR,
ROUND(100*(TOPLAM_SATIS-LISTEFIYATINDAN_SATIS)/LISTEFIYATINDAN_SATIS,2) AS KAR_ZARARYUZDE
FROM(
SELECT
	I.ITEMCODE URUNKODU,
	I.ITEMNAME URUN_ADI,
	I.UNITPRICE LISTE_FIYATI,
	SUM(OD.AMOUNT) TOPLAM_ADET,
	SUM(OD.LINETOTAL) TOPLAM_SATIS,
	MIN(OD.UNITPRICE) ENDUSUK_FIYAT,
	MAX(OD.UNITPRICE) ENYUKSEK_FIYAT,
	ROUND(AVG(OD.UNITPRICE),2) ORTALAMAFIYAT,
	ROUND(SUM(I.UNITPRICE*OD.AMOUNT),0) LISTEFIYATINDAN_SATIS

FROM ITEMS I
JOIN ORDERDETAILS OD ON OD.ITEMID=I.ID
GROUP BY I.ITEMCODE,I.ITEMNAME,I.UNITPRICE
) T
ORDER BY KAR_ZARARYUZDE DESC --DESC YAZARSAN EN COK SATIS BIRSEY YAZILMAZ ISE EN DÜÞÜK--















